export const skillsIconsList = [
  {
    title: "html",
    src: "/assets/icons/html.svg",
    duration: 0.2,
    delay: 0,
  },
  {
    title: "css",
    src: "/assets/icons/css.svg",
    duration: 0.3,
    delay: 0.4,
  },
  {
    title: "js",
    src: "/assets/icons/js.svg",
    duration: 0.3,
    delay: 0.6,
  },
  {
    title: "ts",
    src: "/assets/icons/ts.png",
    duration: 0.3,
    delay: 0.8,
  },
  {
    title: "sass",
    src: "/assets/icons/sass.svg",
    duration: 0.3,
    delay: 1,
  },
  {
    title: "react",
    src: "/assets/icons/react.svg",
    duration: 0.3,
    delay: 1.2,
  },
  {
    title: "next.js",
    src: "/assets/icons/next.png",
    duration: 0.3,
    delay: 1.4,
  },
  {
    title: "tailwind",
    src: "/assets/icons/tailwind.svg",
    duration: 0.3,
    delay: 1.6,
  },
  {
    title: "react hook form",
    src: "/assets/icons/RHF.png",
    duration: 0.3,
    delay: 1.8,
  },
  {
    title: "redux",
    src: "/assets/icons/redux.svg",
    duration: 0.3,
    delay: 2,
  },
  {
    title: "git/github",
    src: "/assets/icons/Git.png",
    duration: 0.3,
    delay: 2.2,
  },
  {
    title: "MUI",
    src: "/assets/icons/mui.png",
    duration: 0.3,
    delay: 2.4,
  },
  {
    title: "React-query",
    src: "/assets/icons/react-quert.png",
    duration: 0.3,
    delay: 2.6,
  },
];
